version: "3"
services:
    adminer:
        image: adminer
        ports:
            - "8082:8080"
        environment:
            ADMINER_DEFAULT_SERVER: db
            ADMINER_DEFAULT_USERNAME: mostafa
            ADMINER_DEFAULT_PASSWORD: 123456789
            ADMINER_DEFAULT_DATABASE: test
    db:
        image: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: test
            MYSQL_USER: mostafa
            MYSQL_PASSWORD: 123456789
